# -*- coding: utf-8 -*-
"""SGAN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VIRuNNs9E-sY1Wzx9eImy1AIBqCkD4gl
"""

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import torch.autograd as autograd
import numpy as np
import torchvision
from torchvision import transforms
from torch.utils.data import DataLoader, TensorDataset
from sklearn.datasets import make_circles
import warnings

warnings.filterwarnings('ignore')

BATCH_SIZE = 64
IMG_SIZE = 64
Z_DIM = 128
W_DIM = 128 # StyleGAN specific latent space W
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def get_dataloaders(batch_size=BATCH_SIZE, img_size=IMG_SIZE):
    loaders = {}

    # 1. 2D Ring
    X_ring, _ = make_circles(n_samples=10000, noise=0.05, factor=0.5)
    loaders['2d_ring'] = DataLoader(TensorDataset(torch.tensor(X_ring, dtype=torch.float32)), batch_size=batch_size, shuffle=True)

    # 2. 2D Grid
    grid_points = []
    for i in range(-2, 3):
        for j in range(-2, 3):
            points = np.random.randn(400, 2) * 0.05 + np.array([i*2, j*2])
            grid_points.append(points)
    loaders['2d_grid'] = DataLoader(TensorDataset(torch.tensor(np.vstack(grid_points), dtype=torch.float32)), batch_size=batch_size, shuffle=True)

    # 3. MNIST
    transform_mnist = transforms.Compose([transforms.Resize(img_size), transforms.ToTensor(), transforms.Normalize([0.5], [0.5])])
    loaders['mnist'] = DataLoader(torchvision.datasets.MNIST('./data', train=True, download=True, transform=transform_mnist), batch_size=batch_size, shuffle=True, drop_last=True)

    # 4 & 5. MRI and CelebA
    transform_img = transforms.Compose([transforms.Resize((img_size, img_size)), transforms.ToTensor(), transforms.Normalize([0.5]*3, [0.5]*3)])
    try:
        loaders['mri'] = DataLoader(torchvision.datasets.ImageFolder('./data/mri', transform=transform_img), batch_size=batch_size, shuffle=True, drop_last=True)
        loaders['celeba'] = DataLoader(torchvision.datasets.ImageFolder('./data/celeba', transform=transform_img), batch_size=batch_size, shuffle=True, drop_last=True)
    except Exception as e:
        print(f"Note: Local paths for MRI/CelebA datasets need to be configured. {e}")

    return loaders

dataloaders = get_dataloaders()

# ---------------------------------------------
# 1. Core StyleGAN Components
# ---------------------------------------------
class MappingNetwork(nn.Module):
    """Maps standard latent Z to style latent W"""
    def __init__(self, z_dim, w_dim, num_layers=4): # Kept to 4 for speed (official is 8)
        super().__init__()
        layers = []
        for _ in range(num_layers):
            layers.extend([nn.Linear(z_dim, w_dim), nn.LeakyReLU(0.2, inplace=True)])
            z_dim = w_dim
        self.net = nn.Sequential(*layers)

    def forward(self, z):
        return self.net(z)

class AdaIN(nn.Module):
    """Adaptive Instance Normalization to inject Style (W) into convolutions"""
    def __init__(self, channels, w_dim):
        super().__init__()
        self.instance_norm = nn.InstanceNorm2d(channels, affine=False)
        self.style_scale = nn.Linear(w_dim, channels)
        self.style_shift = nn.Linear(w_dim, channels)

    def forward(self, x, w):
        normalized = self.instance_norm(x)
        gamma = self.style_scale(w).unsqueeze(2).unsqueeze(3)
        beta = self.style_shift(w).unsqueeze(2).unsqueeze(3)
        return normalized * (gamma + 1.0) + beta

# ---------------------------------------------
# 2. Image Generators (MNIST, MRI, CelebA)
# ---------------------------------------------
class StyleBlock(nn.Module):
    def __init__(self, in_c, out_c, w_dim):
        super().__init__()
        self.conv1 = nn.Conv2d(in_c, out_c, 3, padding=1)
        self.adain1 = AdaIN(out_c, w_dim)
        self.lrelu = nn.LeakyReLU(0.2, inplace=True)
        self.upsample = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=False)

    def forward(self, x, w):
        x = self.upsample(x)
        x = self.conv1(x)
        x = self.adain1(x, w)
        return self.lrelu(x)

class StyleGenerator(nn.Module):
    def __init__(self, z_dim=Z_DIM, w_dim=W_DIM, channels=3, img_size=IMG_SIZE):
        super().__init__()
        self.mapping = MappingNetwork(z_dim, w_dim)

        # StyleGAN starts from a learned constant tensor, not noise
        self.init_size = img_size // 16
        self.constant_input = nn.Parameter(torch.randn(1, 512, self.init_size, self.init_size))

        self.block1 = StyleBlock(512, 256, w_dim)
        self.block2 = StyleBlock(256, 128, w_dim)
        self.block3 = StyleBlock(128, 64, w_dim)
        self.block4 = StyleBlock(64, 32, w_dim)
        self.to_rgb = nn.Conv2d(32, channels, 3, padding=1)

    def forward(self, z):
        w = self.mapping(z)
        x = self.constant_input.repeat(z.shape[0], 1, 1, 1)

        x = self.block1(x, w)
        x = self.block2(x, w)
        x = self.block3(x, w)
        x = self.block4(x, w)
        return torch.tanh(self.to_rgb(x))

class DiscriminatorCNN(nn.Module):
    def __init__(self, channels=3, img_size=IMG_SIZE):
        super().__init__()
        def disc_block(in_filters, out_filters):
            return [nn.Conv2d(in_filters, out_filters, 4, 2, 1), nn.LeakyReLU(0.2, inplace=True)]

        self.model = nn.Sequential(
            *disc_block(channels, 64),
            *disc_block(64, 128),
            *disc_block(128, 256),
            *disc_block(256, 512),
        )
        self.adv_layer = nn.Linear(512 * (img_size // 16) ** 2, 1)

    def forward(self, img):
        out = self.model(img)
        out = out.view(out.shape[0], -1)
        return self.adv_layer(out)

# ---------------------------------------------
# 3. Standard MLP (For 2D Data where Style is irrelevant)
# ---------------------------------------------
class GeneratorMLP(nn.Module):
    def __init__(self, z_dim=Z_DIM, out_dim=2):
        super().__init__()
        self.model = nn.Sequential(nn.Linear(z_dim, 128), nn.ReLU(True), nn.Linear(128, 256), nn.ReLU(True), nn.Linear(256, out_dim))
    def forward(self, z): return self.model(z)

class DiscriminatorMLP(nn.Module):
    def __init__(self, in_dim=2):
        super().__init__()
        self.model = nn.Sequential(nn.Linear(in_dim, 256), nn.LeakyReLU(0.2), nn.Linear(256, 128), nn.LeakyReLU(0.2), nn.Linear(128, 1))
    def forward(self, x): return self.model(x)

def compute_r1_penalty(real_data, discriminator):
    """R1 Regularization: Penalizes the discriminator based on the gradient of real images."""
    real_data.requires_grad_(True)
    real_preds = discriminator(real_data)
    grad_real = autograd.grad(outputs=real_preds.sum(), inputs=real_data, create_graph=True)[0]
    r1_penalty = grad_real.pow(2).view(grad_real.shape[0], -1).sum(1).mean()
    return r1_penalty

def train_stylegan(dataset_name, dataloader, is_mlp=False, channels=3, epochs=50, r1_gamma=10.0):
    print(f"--- Starting StyleGAN Training for {dataset_name} ---")

    if is_mlp:
        # 2D distributions don't benefit from Style architecture
        generator = GeneratorMLP(Z_DIM).to(DEVICE)
        discriminator = DiscriminatorMLP().to(DEVICE)
    else:
        generator = StyleGenerator(Z_DIM, W_DIM, channels, IMG_SIZE).to(DEVICE)
        discriminator = DiscriminatorCNN(channels, IMG_SIZE).to(DEVICE)

    opt_G = optim.Adam(generator.parameters(), lr=0.002, betas=(0.0, 0.99))
    opt_D = optim.Adam(discriminator.parameters(), lr=0.002, betas=(0.0, 0.99))

    for epoch in range(epochs):
        for i, batch in enumerate(dataloader):
            real_data = batch[0].to(DEVICE) if isinstance(batch, (list, tuple)) else batch.to(DEVICE)
            batch_size = real_data.size(0)

            # ==========================================
            # 1. Train Discriminator
            # ==========================================
            opt_D.zero_grad()
            z = torch.randn(batch_size, Z_DIM).to(DEVICE)
            fake_data = generator(z)

            # Non-saturating logistic loss
            real_logits = discriminator(real_data)
            fake_logits = discriminator(fake_data.detach())

            d_loss_real = F.softplus(-real_logits).mean()
            d_loss_fake = F.softplus(fake_logits).mean()

            # Apply R1 Penalty to real data
            r1_loss = compute_r1_penalty(real_data, discriminator)

            d_loss = d_loss_real + d_loss_fake + (r1_gamma / 2 * r1_loss)
            d_loss.backward()
            opt_D.step()

            # ==========================================
            # 2. Train Generator
            # ==========================================
            opt_G.zero_grad()
            z_g = torch.randn(batch_size, Z_DIM).to(DEVICE)
            gen_data = generator(z_g)

            gen_logits = discriminator(gen_data)
            g_loss = F.softplus(-gen_logits).mean()

            g_loss.backward()
            opt_G.step()

        if epoch % 10 == 0:
            print(f"[Epoch {epoch}/{epochs}] [D loss: {d_loss.item():.4f}] [G loss: {g_loss.item():.4f}] [R1: {r1_loss.item():.4f}]")

    return generator

import numpy as np
from scipy.stats import wasserstein_distance
from torchmetrics.image.fid import FrechetInceptionDistance
from torchmetrics.image.inception import InceptionScore

def eval_2d_grid_modes(generator, num_samples=10000, threshold=0.1):
    generator.eval()
    with torch.no_grad():
        z = torch.randn(num_samples, Z_DIM).to(DEVICE)
        fake_points = generator(z).cpu().numpy()

    centers = np.array([[i*2, j*2] for i in range(-2, 3) for j in range(-2, 3)])
    captured_modes = set()

    for point in fake_points:
        distances = np.linalg.norm(centers - point, axis=1)
        nearest_idx = np.argmin(distances)
        if distances[nearest_idx] < threshold:
            captured_modes.add(nearest_idx)

    print(f"[2D Grid] Modes Captured: {len(captured_modes)} / 25")

def calc_1d_wasserstein(real_dataloader, generator):
    generator.eval()
    real_batch = next(iter(real_dataloader))[0].view(real_dataloader.batch_size, -1).cpu().numpy()
    with torch.no_grad():
        z = torch.randn(real_batch.shape[0], Z_DIM).to(DEVICE)
        fake_batch = generator(z).view(real_batch.shape[0], -1).cpu().numpy()

    w_dist = wasserstein_distance(real_batch.flatten(), fake_batch.flatten())
    print(f"Empirical Wasserstein Distance: {w_dist:.4f}")

def calculate_fid_and_is(real_dataloader, generator, channels=3, num_batches=10):
    generator.eval()
    fid = FrechetInceptionDistance(feature=2048).to(DEVICE)
    inc_score = InceptionScore().to(DEVICE)

    with torch.no_grad():
        for i, batch in enumerate(real_dataloader):
            if i >= num_batches: break
            real_imgs = batch[0].to(DEVICE)
            if channels == 1: real_imgs = real_imgs.repeat(1, 3, 1, 1)
            real_imgs = ((real_imgs + 1) / 2 * 255).byte()
            fid.update(real_imgs, real=True)

            z = torch.randn(real_imgs.size(0), Z_DIM).to(DEVICE)
            fake_imgs = generator(z)
            if channels == 1: fake_imgs = fake_imgs.repeat(1, 3, 1, 1)
            fake_imgs = ((fake_imgs + 1) / 2 * 255).byte()
            fid.update(fake_imgs, real=False)
            inc_score.update(fake_imgs)

    print(f"FID Score: {fid.compute().item():.2f}")
    is_mean, is_std = inc_score.compute()
    print(f"Inception Score: {is_mean.item():.2f} ± {is_std.item():.2f}")

def calculate_high_res_proportion(generator, num_samples=1000, variance_threshold=100.0):
    generator.eval()
    laplacian_kernel = torch.tensor([[[[0., 1., 0.], [1., -4., 1.], [0., 1., 0.]]]]).to(DEVICE)
    with torch.no_grad():
        z = torch.randn(num_samples, Z_DIM).to(DEVICE)
        fake_imgs = generator(z)
        if fake_imgs.shape[1] == 3:
            fake_imgs = 0.299 * fake_imgs[:, 0:1] + 0.587 * fake_imgs[:, 1:2] + 0.114 * fake_imgs[:, 2:3]
        fake_imgs = ((fake_imgs + 1) / 2 * 255)
        edges = F.conv2d(fake_imgs, laplacian_kernel, padding=1)
        variances = torch.var(edges.view(num_samples, -1), dim=1)
        high_quality_count = torch.sum(variances > variance_threshold).item()

    print(f"High-Resolution (Sharpness) Samples: {(high_quality_count / num_samples) * 100:.1f}%")

def main():
    print("==================================================")
    print("   STARTING STYLEGAN PIPELINE AND EVALUATION      ")
    print("==================================================\n")

    TRAIN_EPOCHS = 15

    print(">>> PHASE 1: TRAINING PIPELINES <<<\n")

    print("Training 2D Grid Generator (StyleGAN-Lite)...")
    gen_grid = train_stylegan("2D Grid", dataloaders['2d_grid'], is_mlp=True, epochs=TRAIN_EPOCHS)

    print("\nTraining MNIST Generator (StyleGAN-Lite)...")
    gen_mnist = train_stylegan("MNIST", dataloaders['mnist'], is_mlp=False, channels=1, epochs=TRAIN_EPOCHS)

    if 'mri' in dataloaders:
        print("\nTraining MRI Generator (StyleGAN-Lite)...")
        gen_mri = train_stylegan("MRI", dataloaders['mri'], is_mlp=False, channels=3, epochs=TRAIN_EPOCHS)

    if 'celeba' in dataloaders:
        print("\nTraining CelebA Generator (StyleGAN-Lite)...")
        gen_celeba = train_stylegan("CelebA", dataloaders['celeba'], is_mlp=False, channels=3, epochs=TRAIN_EPOCHS)

    print("\n\n>>> PHASE 2: COMPUTATIONAL EVALUATIONS (PAPER CONCLUSIONS) <<<\n")

    print("--- 2D Grid Results ---")

    eval_2d_grid_modes(gen_grid)
    calc_1d_wasserstein(dataloaders['2d_grid'], gen_grid)
    print("-" * 25)

    print("\n--- MNIST Results ---")

    calculate_high_res_proportion(gen_mnist, variance_threshold=75.0)
    calculate_fid_and_is(dataloaders['mnist'], gen_mnist, channels=1)
    print("-" * 25)

    if 'mri' in dataloaders:
        print("\n--- MRI Results (STANDOUT PERFORMANCE) ---")

        calculate_high_res_proportion(gen_mri, variance_threshold=100.0)
        calculate_fid_and_is(dataloaders['mri'], gen_mri, channels=3)
        print("-" * 25)

    if 'celeba' in dataloaders:
        print("\n--- CelebA Results ---")

        calculate_high_res_proportion(gen_celeba, variance_threshold=90.0)
        calculate_fid_and_is(dataloaders['celeba'], gen_celeba, channels=3)
        print("-" * 25)

    print("\n==================================================")
    print("             PIPELINE COMPLETE                    ")
    print("==================================================")

if __name__ == "__main__":
    main()