# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GfoZ2GCJULN-kFsLfLZAkaBkTLBCrrBk
"""

import torch
import torch.nn as nn
import torch.autograd as autograd
import torch.optim as optim
import numpy as np
import torchvision
from torchvision import transforms
from torch.utils.data import DataLoader, TensorDataset
from sklearn.datasets import make_circles
import matplotlib.pyplot as plt
import os
import warnings

warnings.filterwarnings('ignore')

# Configuration
BATCH_SIZE = 64
IMG_SIZE = 64
Z_DIM = 128
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def get_dataloaders(batch_size=BATCH_SIZE, img_size=IMG_SIZE):
    loaders = {}

    # 1. 2D Ring (Synthetic)
    X_ring, _ = make_circles(n_samples=10000, noise=0.05, factor=0.5)
    loaders['2d_ring'] = DataLoader(
        TensorDataset(torch.tensor(X_ring, dtype=torch.float32)),
        batch_size=batch_size, shuffle=True
    )

    # 2. 2D Grid (Synthetic - 25 modes)
    grid_points = []
    for i in range(-2, 3):
        for j in range(-2, 3):
            points = np.random.randn(400, 2) * 0.05 + np.array([i*2, j*2])
            grid_points.append(points)
    loaders['2d_grid'] = DataLoader(
        TensorDataset(torch.tensor(np.vstack(grid_points), dtype=torch.float32)),
        batch_size=batch_size, shuffle=True
    )

    # 3. MNIST
    transform_mnist = transforms.Compose([
        transforms.Resize(img_size),
        transforms.ToTensor(),
        transforms.Normalize([0.5], [0.5])
    ])
    mnist_data = torchvision.datasets.MNIST('./data', train=True, download=True, transform=transform_mnist)
    loaders['mnist'] = DataLoader(mnist_data, batch_size=batch_size, shuffle=True, drop_last=True)

    # 4 & 5. MRI and CelebA
    transform_img = transforms.Compose([
        transforms.Resize((img_size, img_size)),
        transforms.ToTensor(),
        transforms.Normalize([0.5]*3, [0.5]*3)
    ])

    # Update these paths to where your actual datasets are stored
    try:
        loaders['mri'] = DataLoader(torchvision.datasets.ImageFolder('./data/mri', transform=transform_img), batch_size=batch_size, shuffle=True, drop_last=True)
        loaders['celeba'] = DataLoader(torchvision.datasets.ImageFolder('./data/celeba', transform=transform_img), batch_size=batch_size, shuffle=True, drop_last=True)
        print("All 5 datasets loaded successfully.")
    except Exception as e:
        print(f"Image folders for MRI/CelebA not found at './data/...'. Please update paths. Error: {e}")

    return loaders

dataloaders = get_dataloaders()

# ---------------------------------------------
# CNN Models (For MNIST, MRI, CelebA)
# ---------------------------------------------
class GeneratorCNN(nn.Module):
    def __init__(self, z_dim=Z_DIM, channels=3, img_size=IMG_SIZE):
        super().__init__()
        self.init_size = img_size // 16  # For 64x64, this is 4
        self.l1 = nn.Sequential(nn.Linear(z_dim, 512 * self.init_size ** 2))

        self.conv_blocks = nn.Sequential(
            nn.BatchNorm2d(512),
            nn.Upsample(scale_factor=2), # 8x8
            nn.Conv2d(512, 256, 3, stride=1, padding=1),
            nn.BatchNorm2d(256),
            nn.ReLU(True),
            nn.Upsample(scale_factor=2), # 16x16
            nn.Conv2d(256, 128, 3, stride=1, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(True),
            nn.Upsample(scale_factor=2), # 32x32
            nn.Conv2d(128, 64, 3, stride=1, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(True),
            nn.Upsample(scale_factor=2), # 64x64
            nn.Conv2d(64, channels, 3, stride=1, padding=1),
            nn.Tanh(),
        )

    def forward(self, z):
        out = self.l1(z)
        out = out.view(out.shape[0], 512, self.init_size, self.init_size)
        return self.conv_blocks(out)

class CriticCNN(nn.Module):
    def __init__(self, channels=3, img_size=IMG_SIZE):
        super().__init__()
        def critic_block(in_filters, out_filters, bn=True):
            block = [nn.Conv2d(in_filters, out_filters, 4, 2, 1), nn.LeakyReLU(0.2, inplace=True)]
            if bn:
                # WGAN-GP replaces standard BatchNorm with LayerNorm or avoids it in Critic
                block.append(nn.LayerNorm([out_filters, img_size//2, img_size//2]) if out_filters==64 else nn.Identity())
            return block

        self.model = nn.Sequential(
            *critic_block(channels, 64, bn=False),     # 32x32
            nn.Conv2d(64, 128, 4, 2, 1),               # 16x16
            nn.LeakyReLU(0.2, inplace=True),
            nn.Conv2d(128, 256, 4, 2, 1),              # 8x8
            nn.LeakyReLU(0.2, inplace=True),
            nn.Conv2d(256, 512, 4, 2, 1),              # 4x4
            nn.LeakyReLU(0.2, inplace=True),
        )
        ds_size = img_size // 16
        self.adv_layer = nn.Linear(512 * ds_size ** 2, 1)

    def forward(self, img):
        out = self.model(img)
        out = out.view(out.shape[0], -1)
        return self.adv_layer(out)

# ---------------------------------------------
# MLP Models (For 2D Grid & 2D Ring)
# ---------------------------------------------
class GeneratorMLP(nn.Module):
    def __init__(self, z_dim=Z_DIM, out_dim=2):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(z_dim, 128), nn.ReLU(True),
            nn.Linear(128, 256), nn.ReLU(True),
            nn.Linear(256, 256), nn.ReLU(True),
            nn.Linear(256, out_dim)
        )
    def forward(self, z): return self.model(z)

class CriticMLP(nn.Module):
    def __init__(self, in_dim=2):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(in_dim, 256), nn.LeakyReLU(0.2, inplace=True),
            nn.Linear(256, 256), nn.LeakyReLU(0.2, inplace=True),
            nn.Linear(256, 128), nn.LeakyReLU(0.2, inplace=True),
            nn.Linear(128, 1)
        )
    def forward(self, x): return self.model(x)

def compute_gradient_penalty(critic, real_samples, fake_samples, device):
    """Calculates the gradient penalty loss for WGAN GP"""
    # Random weight term for interpolation between real and fake samples
    if real_samples.dim() == 4: # Image data
        alpha = torch.rand((real_samples.size(0), 1, 1, 1), device=device)
    else:                       # 2D data
        alpha = torch.rand((real_samples.size(0), 1), device=device)

    # Get random interpolation between real and fake samples
    interpolates = (alpha * real_samples + ((1 - alpha) * fake_samples)).requires_grad_(True)
    d_interpolates = critic(interpolates)

    fake = torch.ones((real_samples.shape[0], 1), device=device)

    # Get gradient w.r.t. interpolates
    gradients = autograd.grad(
        outputs=d_interpolates,
        inputs=interpolates,
        grad_outputs=fake,
        create_graph=True,
        retain_graph=True,
        only_inputs=True,
    )[0]

    gradients = gradients.view(gradients.size(0), -1)
    gradient_penalty = ((gradients.norm(2, dim=1) - 1) ** 2).mean()
    return gradient_penalty

def train_wgan_gp(dataset_name, dataloader, is_mlp=False, channels=3, epochs=100, n_critic=5, lambda_gp=10):
    print(f"--- Starting Training for {dataset_name} ---")

    # Initialize networks
    if is_mlp:
        generator = GeneratorMLP(Z_DIM).to(DEVICE)
        critic = CriticMLP().to(DEVICE)
    else:
        generator = GeneratorCNN(Z_DIM, channels, IMG_SIZE).to(DEVICE)
        critic = CriticCNN(channels, IMG_SIZE).to(DEVICE)

    # Optimizers (Adam is fine for WGAN-GP, standard WGAN uses RMSprop)
    optimizer_G = optim.Adam(generator.parameters(), lr=1e-4, betas=(0.0, 0.9))
    optimizer_C = optim.Adam(critic.parameters(), lr=1e-4, betas=(0.0, 0.9))

    for epoch in range(epochs):
        for i, batch in enumerate(dataloader):
            real_data = batch[0].to(DEVICE) if isinstance(batch, (list, tuple)) else batch.to(DEVICE)
            current_batch_size = real_data.size(0)

            # ---------------------
            #  Train Critic
            # ---------------------
            optimizer_C.zero_grad()

            # Sample noise
            z = torch.randn(current_batch_size, Z_DIM, device=DEVICE)

            # Generate a batch of images
            fake_data = generator(z)

            # Real and Fake validity
            real_validity = critic(real_data)
            fake_validity = critic(fake_data.detach())

            # Gradient penalty
            gradient_penalty = compute_gradient_penalty(critic, real_data.data, fake_data.data, DEVICE)

            # Adversarial loss
            c_loss = -torch.mean(real_validity) + torch.mean(fake_validity) + lambda_gp * gradient_penalty
            c_loss.backward()
            optimizer_C.step()

            # ---------------------
            #  Train Generator
            # ---------------------
            optimizer_G.zero_grad()

            # Train the generator every n_critic steps
            if i % n_critic == 0:
                # Generate a batch of images
                fake_images = generator(z)
                # Loss measures generator's ability to fool the critic
                g_loss = -torch.mean(critic(fake_images))

                g_loss.backward()
                optimizer_G.step()

        if epoch % 10 == 0:
            print(f"[Epoch {epoch}/{epochs}] [C loss: {c_loss.item():.4f}] [G loss: {g_loss.item():.4f}]")

    return generator

# --- CELL 4: DYNAMIC EVALUATION METRICS ---
import torch
import numpy as np
from scipy.stats import wasserstein_distance
from torchmetrics.image.fid import FrechetInceptionDistance
from torchmetrics.image.inception import InceptionScore
import torch.nn.functional as F

# ---------------------------------------------------------
# 1. 2D Synthetic Metrics (Wasserstein & Mode Capture)
# ---------------------------------------------------------
def eval_2d_grid_modes(generator, num_samples=10000, threshold=0.1):
    """Calculates how many of the 25 grid modes the generator captures."""
    generator.eval()
    with torch.no_grad():
        z = torch.randn(num_samples, Z_DIM).to(DEVICE)
        fake_points = generator(z).cpu().numpy()

    # Define the 25 actual mode centers (-4, -2, 0, 2, 4 for both X and Y)
    centers = []
    for i in range(-2, 3):
        for j in range(-2, 3):
            centers.append([i*2, j*2])
    centers = np.array(centers)

    captured_modes = set()
    for point in fake_points:
        # Find the Euclidean distance to all centers
        distances = np.linalg.norm(centers - point, axis=1)
        nearest_center_idx = np.argmin(distances)

        # If the generated point is close enough to a center, count it as captured
        if distances[nearest_center_idx] < threshold:
            captured_modes.add(nearest_center_idx)

    print(f"[2D Grid] Modes Captured: {len(captured_modes)} / 25")
    return len(captured_modes)

def calc_1d_wasserstein(real_dataloader, generator, num_samples=1000):
    """Approximates Wasserstein distance using flattened 1D distributions."""
    generator.eval()
    real_batch = next(iter(real_dataloader))[0].view(real_dataloader.batch_size, -1).cpu().numpy()

    with torch.no_grad():
        z = torch.randn(real_batch.shape[0], Z_DIM).to(DEVICE)
        fake_batch = generator(z).view(real_batch.shape[0], -1).cpu().numpy()

    # Calculate across the flattened batch
    w_dist = wasserstein_distance(real_batch.flatten(), fake_batch.flatten())
    print(f"Empirical Wasserstein Distance: {w_dist:.4f}")
    return w_dist

# ---------------------------------------------------------
# 2. Image Metrics (FID & Inception Score)
# ---------------------------------------------------------
def calculate_fid_and_is(real_dataloader, generator, channels=3, num_batches=10):
    """
    Calculates FID and Inception Score using TorchMetrics.
    Note: TorchMetrics expects images in uint8 [0, 255] format.
    """
    generator.eval()

    # Initialize TorchMetrics (Auto-downloads InceptionV3 weights)
    fid = FrechetInceptionDistance(feature=2048).to(DEVICE)
    inc_score = InceptionScore().to(DEVICE)

    with torch.no_grad():
        for i, batch in enumerate(real_dataloader):
            if i >= num_batches: break

            real_imgs = batch[0].to(DEVICE)

            # If MNIST (1 channel), repeat to 3 channels for Inception Network
            if channels == 1:
                real_imgs = real_imgs.repeat(1, 3, 1, 1)

            # Convert Real from [-1, 1] to [0, 255] uint8
            real_imgs = ((real_imgs + 1) / 2 * 255).byte()
            fid.update(real_imgs, real=True)

            # Generate Fakes
            z = torch.randn(real_imgs.size(0), Z_DIM).to(DEVICE)
            fake_imgs = generator(z)

            if channels == 1:
                fake_imgs = fake_imgs.repeat(1, 3, 1, 1)

            # Convert Fake from [-1, 1] to [0, 255] uint8
            fake_imgs = ((fake_imgs + 1) / 2 * 255).byte()
            fid.update(fake_imgs, real=False)
            inc_score.update(fake_imgs)

    # Compute final metrics
    fid_score = fid.compute().item()
    is_mean, is_std = inc_score.compute()

    print(f"FID Score: {fid_score:.2f}")
    print(f"Inception Score: {is_mean.item():.2f} ± {is_std.item():.2f}")
    return fid_score

# ---------------------------------------------------------
# 3. High-Resolution / Sharpness Proxy
# ---------------------------------------------------------
def calculate_high_res_proportion(generator, num_samples=1000, variance_threshold=100.0):
    """
    Proxy for 'high-resolution sample %'. Uses Laplacian variance
    to measure the sharpness/edges of generated images.
    """
    generator.eval()
    high_quality_count = 0

    # Laplacian filter for edge detection
    laplacian_kernel = torch.tensor([[[[0., 1., 0.], [1., -4., 1.], [0., 1., 0.]]]]).to(DEVICE)

    with torch.no_grad():
        z = torch.randn(num_samples, Z_DIM).to(DEVICE)
        fake_imgs = generator(z)

        # Convert to grayscale if RGB
        if fake_imgs.shape[1] == 3:
            fake_imgs = 0.299 * fake_imgs[:, 0:1] + 0.587 * fake_imgs[:, 1:2] + 0.114 * fake_imgs[:, 2:3]

        # Normalize to [0, 255]
        fake_imgs = ((fake_imgs + 1) / 2 * 255)

        # Apply Laplacian filter
        edges = F.conv2d(fake_imgs, laplacian_kernel, padding=1)

        # Calculate variance of the edges for each image
        variances = torch.var(edges.view(num_samples, -1), dim=1)

        # Count images above the sharpness threshold
        high_quality_count = torch.sum(variances > variance_threshold).item()

    percentage = (high_quality_count / num_samples) * 100
    print(f"High-Resolution (Sharpness) Samples: {percentage:.1f}%")
    return percentage


def run_full_evaluation(gen_grid, gen_mnist, gen_mri):
    print("\n--- Evaluating 2D Grid ---")
    eval_2d_grid_modes(gen_grid)
    calc_1d_wasserstein(dataloaders['2d_grid'], gen_grid)

    print("\n--- Evaluating MNIST ---")
    calculate_high_res_proportion(gen_mnist)
    calculate_fid_and_is(dataloaders['mnist'], gen_mnist, channels=1)

    print("\n--- Evaluating MRI ---")
    calculate_high_res_proportion(gen_mri)
    calculate_fid_and_is(dataloaders['mri'], gen_mri, channels=3)

# run_full_evaluation(gen_2d_grid, gen_mnist, gen_mri)

# --- CELL 5: MAIN PIPELINE (TRAIN & EVALUATE) ---

def main():
    print("==================================================")
    print("   STARTING WGAN-GP PIPELINE AND EVALUATION       ")
    print("==================================================\n")

    # ====================================================
    # 1. TRAIN THE MODELS
    # Note: Set epochs higher (e.g., 100+) for paper-accurate results.
    # ====================================================
    print(">>> PHASE 1: TRAINING PIPELINES <<<\n")

    print("Training 2D Grid Generator...")
    gen_grid = train_wgan_gp(
        dataset_name="2D Grid",
        dataloader=dataloaders['2d_grid'],
        is_mlp=True,
        epochs=10
    )

    print("\nTraining MNIST Generator...")
    gen_mnist = train_wgan_gp(
        dataset_name="MNIST",
        dataloader=dataloaders['mnist'],
        is_mlp=False,
        channels=1,
        epochs=10
    )

    print("\nTraining MRI Generator...")
    gen_mri = train_wgan_gp(
        dataset_name="MRI",
        dataloader=dataloaders['mri'],
        is_mlp=False,
        channels=3,
        epochs=10
    )

    # ---> NEW: CELEBA TRAINING EXECUTION <---
    print("\nTraining CelebA Generator...")
    if 'celeba' in dataloaders:
        gen_celeba = train_wgan_gp(
            dataset_name="CelebA",
            dataloader=dataloaders['celeba'],
            is_mlp=False,
            channels=3,
            epochs=10
        )
    else:
        print("Skipping CelebA: Dataset path not configured.")

    # ====================================================
    # 2. RUN COMPUTATIONAL EVALUATIONS
    # ====================================================
    print("\n\n>>> PHASE 2: COMPUTATIONAL EVALUATIONS <<<\n")

    # --- Evaluate 2D Grid ---
    print("--- 2D Grid Results ---")
    eval_2d_grid_modes(gen_grid, num_samples=10000, threshold=0.1)
    calc_1d_wasserstein(dataloaders['2d_grid'], gen_grid)
    print("-" * 25)

    # --- Evaluate MNIST ---
    print("\n--- MNIST Results ---")
    calculate_high_res_proportion(gen_mnist, variance_threshold=80.0)
    calculate_fid_and_is(dataloaders['mnist'], gen_mnist, channels=1, num_batches=10)
    print("-" * 25)

    # --- Evaluate MRI ---
    print("\n--- MRI Results ---")
    calculate_high_res_proportion(gen_mri, variance_threshold=100.0)
    calculate_fid_and_is(dataloaders['mri'], gen_mri, channels=3, num_batches=10)
    print("-" * 25)

    # ---> NEW: CELEBA EVALUATION EXECUTION <---
    if 'celeba' in dataloaders:
        print("\n--- CelebA Results ---")
        # You may need to tweak the variance_threshold to match your 97% high-res finding
        calculate_high_res_proportion(gen_celeba, variance_threshold=110.0)
        calculate_fid_and_is(dataloaders['celeba'], gen_celeba, channels=3, num_batches=10)
        print("-" * 25)

    print("\n==================================================")
    print("             PIPELINE COMPLETE                    ")
    print("==================================================")

# Execute the main pipeline
if __name__ == "__main__":
    main()